apiVersion: v1
entries:
  purelb:
  - apiVersion: v2
    appVersion: v0.14.1
    created: "2026-02-02T17:19:53.670460824Z"
    description: PureLB is a Kubernetes load-balancer controller that uses standard
      Linux networking and routing protocols.
    digest: 548bc86cf9bbcfb9e914a0035238969c1158e33f775816589577f43e2a015a97
    keywords:
    - load-balancer
    - balancer
    - lb
    - bgp
    - arp
    - vrrp
    - vip
    name: purelb
    sources:
    - https://github.com/purelb/purelb
    type: application
    urls:
    - https://github.com/purelb/purelb/releases/download/purelb-v0.14.1.tgz
    version: v0.14.1
  - apiVersion: v2
    appVersion: v0.14.0
    created: "2026-02-02T17:19:53.669764067Z"
    description: PureLB is a Kubernetes load-balancer controller that uses standard
      Linux networking and routing protocols.
    digest: 559149e7593a732df3770ba58674b9ff2ad91902cc56ad7894f1436b36defbed
    keywords:
    - load-balancer
    - balancer
    - lb
    - bgp
    - arp
    - vrrp
    - vip
    name: purelb
    sources:
    - https://github.com/purelb/purelb
    type: application
    urls:
    - https://github.com/purelb/purelb/releases/download/purelb-v0.14.0.tgz
    version: v0.14.0
generated: "2026-02-02T17:19:53.668696916Z"
