apiVersion: purelb.io/v2
kind: ServiceGroup
metadata:
  name: default
spec:
  local:
    v6pool:
      subnet: 'fd53:9ef0:8683::/120'
      pool: 'fd53:9ef0:8683::-fd53:9ef0:8683::3'
      aggregation: default
